name: Python CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests with pytest
      run: |
        pytest tests/ -v --tb=short
    
    - name: Test CLI functionality
      run: |
        python -m src.wedding_table_match.cli \
          --guests data/guests.csv \
          --tables data/tables.csv \
          --relationships data/relationships.csv \
          --output test_output.txt \
          --verbose
        
        # Check that output file was created
        test -f test_output.txt && echo "CLI test passed" || exit 1